services:
  mc-dcbot:
    image: mc37_dcbot
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mc-dcbot
    restart: unless-stopped
    networks:
      - minecraft_dc_network

networks:
  minecraft_dc_network:
    external: true
    name: minecraft37_network
